package com.linkedbear.springboot.assemble.a_b_c_module_profile_conditional.config

import com.linkedbear.springboot.assemble.a_b_c_module_profile_conditional.anno.EnableTavern
import org.springframework.context.annotation.Configuration

@Configuration
@EnableTavern
open class TavernConfiguration